language:
  node_js
  - 9
# @TODO: fix sudo workaround
# https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm install -g @angular/cli codecov
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - codecov
